# Generated by Django 5.2.11 on 2026-02-23 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_portal', '0001_initial'),
        ('students', '0002_remove_certification_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HRSharedStudent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('hr_user', models.ForeignKey(limit_choices_to={'role': 'HR'}, on_delete=django.db.models.deletion.CASCADE, related_name='shared_students', to=settings.AUTH_USER_MODEL)),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_students_by_admin', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_shared_entries', to='students.studentprofile')),
            ],
            options={
                'unique_together': {('hr_user', 'student')},
            },
        ),
    ]
