# Generated by Django 5.2.11 on 2026-02-20 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('year', models.CharField(max_length=20)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollegeSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('college', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.college')),
                ('current_academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_portal.academicyear')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
